// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgkndudeywcomrxuxxyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impna25kdWRleXdjb21yeHV4eHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjkwNjIsImV4cCI6MjA2NzA0NTA2Mn0.BlT5K8noOdroeV_rXcLEpu3JMTSvp36dTNKaOsVedDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});